### PR TITLE
colorize current context in `d.rymcg.tech context`

### PR DESCRIPTION
**Pull request by mcmikemn**
Changed `d.rymcg.tech context` to display the current context in green so it stands out better.

### CODE REVIEW

**Comment by EnigmaCurry** [comment]
This is a nice idea. Recently I added the [color](https://github.com/EnigmaCurry/d.rymcg.tech/blob/2594f8e30a1db3f8e6e7f7c6e5aa9bd80a813876/_scripts/funcs.sh#L197-L230) function and I would like to consolidate and use that for all text coloring. 

So I think this can be replaced with:

```
        output=$(docker context ls)
        color "light green" "${output}"
```

**Comment by EnigmaCurry** [comment]
you'd still need the code you're doing to print only the one line out of the output

**Comment by EnigmaCurry** [comment]
this might be more efficient

```
d.rymcg.tech context | GREP_COLORS="mt=01;32" grep --color -E '^.* \* .*$|'
```

grep matches for * and greedily expands to that whole line and colors it green.

I want to see if I can generalize that into a reusable function

**Comment by EnigmaCurry** [comment]
LOL you can make it blink 

```
d.rymcg.tech context | GREP_COLORS="ms=05;32" grep --color -E '^.* \* .*$|'
```

**Comment by EnigmaCurry** [comment]
I added a similar `colorize` that reads from stdin and highlights matches.

```
d.rymcg.tech context | colorize green ' \* '
```

wdyt?

**Comment by mcmikemn** [comment]
Awesome.

**Comment by mcmikemn** [comment]
But no blinking. :)

**Pull request merged**
