### PR TITLE
chore(Makefile): update target for 'userns-remap'

### PR DESCRIPTION
**Pull request by ZarTek-Creole**
feat(Makefile): add support for 'userns-remap on' and 'userns-remap off' commands to configure Docker server for User/Root Namespace Remap
fix(_scripts/userns-remap): update command argument handling to include descriptions for 'on', 'off', and 'check' options

PR for https://github.com/EnigmaCurry/d.rymcg.tech/pull/180#issuecomment-1916596013

### CODE REVIEW

**Comment by ZarTek-Creole** [comment]
for https://github.com/EnigmaCurry/d.rymcg.tech/pull/180#issuecomment-1916596013

**Comment by EnigmaCurry** [comment]
Wow. I've never seen `$(filter-out $@,$(MAKECMDGOALS))` before. I never knew you could make an argument to make like that.

Previously, I was under the impression that:
 * Single words like `config` and `install` are make TARGETS.
 * You can combine several words to chain commands, eg. `make config install`.
 * Make arguments require an `=` symbol. like `make install service=frontend`.

Adding extra non target, non `=` args would break this idea.

What would `make userns-remap off config install` do? In my previous thinking `off` would be its own target.

I have to think more about this. It would be fine for `userns-remap` because its not likely you would want to chanin commands. But if we do it here, we might do it elsewhere, and so it might break a lot of assumptions I was making. Thanks for bringing this technique to my attention.

**Comment by EnigmaCurry** [comment]
The cleaner solution to be compatible with my prior thinking would be something like `make userns-remap enabled=true` and if you just did `make userns-remap` it would ask you interactively should it be on or off.

**Comment by EnigmaCurry** [comment]
I'm inclined to close this for now as I don't want to change the previous convention for named arguments. Thanks again for showing me this cool trick though :+1:

**Pull request closed without merging**
