### PR TITLE
Add bind-mount host / to Glances

### PR DESCRIPTION
**Pull request by mcmikemn**
I added the ability to bnd mount `/` on host so Glances could report on disk space available on the host. What do you think?

### CODE REVIEW

**Review by EnigmaCurry — APPROVED** [review]

**Review by EnigmaCurry — CHANGES_REQUESTED** [review]
Can we rename the var like GLANCES_MOUNT_HOST_FILESYSTEM ?

**Comment by EnigmaCurry** [comment]
Please test with an additional mounted volume too, does it get reported as well?

**Comment by mcmikemn** [comment]
> Can we rename the var like GLANCES_MOUNT_HOST_FILESYSTEM ?

Fixed in [95ba59e](https://github.com/EnigmaCurry/d.rymcg.tech/pull/286/commits/95ba59e755cee4f48934cc754a6835bfc96e12f2)

**Comment by mcmikemn** [comment]
> Please test with an additional mounted volume too, does it get reported as well?

Yes, Glances can report on multiple disks and/or filesystem mounts.

**Review by EnigmaCurry — APPROVED** [review]

**Pull request merged**
